# Generated by Django 4.1.5 on 2023-02-01 04:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('name', models.CharField(max_length=200)),
                ('room', models.CharField(max_length=10)),
                ('branch', models.CharField(max_length=10)),
                ('year', models.CharField(max_length=10)),
                ('usn', models.CharField(max_length=12)),
                ('pAdd', models.CharField(max_length=250)),
                ('mobile', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=254)),
                ('img', models.CharField(max_length=200)),
                ('blood', models.CharField(max_length=10)),
            ],
        ),
    ]
