# Generated by Django 4.1.5 on 2023-02-01 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseapp', '0002_alter_student_blood_alter_student_branch_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='blood',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='student',
            name='branch',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='student',
            name='pAdd',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='student',
            name='year',
            field=models.CharField(max_length=10),
        ),
    ]
