# Generated by Django 4.1.6 on 2023-02-07 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseapp', '0004_remove_student_user_alter_student_usn'),
    ]

    operations = [
        migrations.CreateModel(
            name='MagStaff',
            fields=[
                ('email', models.EmailField(max_length=254, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('designation', models.CharField(max_length=30)),
                ('mobile', models.CharField(blank=True, max_length=10)),
            ],
        ),
    ]
