# Generated by Django 4.1.6 on 2023-02-11 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseapp', '0007_alter_holiday_enddate_alter_holiday_startdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='onHoliday',
            field=models.BooleanField(default=False),
        ),
    ]
