# Generated by Django 4.1.6 on 2023-02-12 05:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('baseapp', '0009_alter_holiday_enddate_alter_holiday_numberofdays'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='holiday',
            unique_together={('usn', 'startDate')},
        ),
    ]
