# Generated by Django 4.1.6 on 2023-02-12 05:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('baseapp', '0010_alter_holiday_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='holiday',
            unique_together=set(),
        ),
    ]
