# Generated by Django 4.1.6 on 2023-02-13 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseapp', '0012_complaints_reviews'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='gender',
            field=models.CharField(default='M', max_length=1),
            preserve_default=False,
        ),
    ]
